export type InteractionBaseline =
  | "functional-covered"
  | "functional-uncovered"
  | "unwired"
  | "missing";

export type DeliveryMilestone =
  | "M1"
  | "M2"
  | "M3"
  | "M4"
  | "M5"
  | "M6"
  | "M7"
  | "M8"
  | "M9";

export interface InteractionContract {
  id: string;
  surface: string;
  control: string;
  behavior: string;
  baseline: InteractionBaseline;
  milestone: DeliveryMilestone;
  states: readonly string[];
  testIds: readonly string[];
}

export type CoverageViewport = "desktop" | "tablet" | "mobile";
export type CoverageStateKind =
  | "behavior"
  | "async"
  | "empty"
  | "error"
  | "auth";

export interface UiCoverageContract extends InteractionContract {
  route: string;
  viewports: readonly CoverageViewport[];
  rtlTestIds: readonly string[];
  playwrightTestIds: readonly string[];
  playwrightStateTestIds: readonly {
    state: string;
    testIds: readonly string[];
  }[];
  screenshotIds: readonly string[];
  classifiedStates: readonly {
    name: string;
    kind: CoverageStateKind;
  }[];
}

const STANDARD_STATES = [
  "ready",
  "keyboard",
  "disabled",
  "loading",
  "success",
  "error",
] as const;

const NAVIGATION_STATES = ["ready", "keyboard", "selected", "mobile"] as const;

export const INTERACTION_MANIFEST: readonly InteractionContract[] = [
  {
    id: "shell.navigation.open-mobile",
    surface: "Shell",
    control: "Open navigation",
    behavior: "Opens the mobile project navigation and moves focus into it.",
    baseline: "functional-covered",
    milestone: "M1",
    states: NAVIGATION_STATES,
    testIds: ["pw.mobile-navigation", "jest.mobile-navigation"],
  },
  {
    id: "shell.navigation.close-mobile",
    surface: "Shell",
    control: "Close navigation and scrim",
    behavior: "Closes mobile navigation by button, scrim, or Escape and restores focus.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: NAVIGATION_STATES,
    testIds: ["pw.mobile-navigation", "pw.keyboard-shell"],
  },
  {
    id: "shell.navigation.primary-routes",
    surface: "Shell",
    control: "Overview, Library, Runs, Settings, and studio navigation",
    behavior: "Navigates to a URL-addressable view and preserves back/forward/refresh state.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: NAVIGATION_STATES,
    testIds: ["pw.route-state", "jest.primary-navigation"],
  },
  {
    id: "shell.search.open",
    surface: "Shell",
    control: "Search workspace and Ctrl/Cmd+K",
    behavior: "Opens the command palette, traps focus, and focuses the query.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: ["ready", "keyboard", "open", "mobile"],
    testIds: ["pw.command-palette"],
  },
  {
    id: "shell.search.query",
    surface: "Shell",
    control: "Workspace search query",
    behavior: "Filters authorized routes and records with empty and no-result states.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: ["ready", "typing", "empty", "no-results"],
    testIds: ["pw.command-palette"],
  },
  {
    id: "shell.search.select-result",
    surface: "Shell",
    control: "Command result",
    behavior: "Navigates with pointer or keyboard and closes the palette.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: ["ready", "keyboard", "selected"],
    testIds: ["pw.command-palette"],
  },
  {
    id: "shell.search.close",
    surface: "Shell",
    control: "Close search and Escape",
    behavior: "Closes the dialog and restores focus to the trigger.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: ["open", "keyboard", "closed"],
    testIds: ["pw.command-palette"],
  },
  {
    id: "shell.approvals.open",
    surface: "Shell",
    control: "Pending approvals notification",
    behavior: "Navigates to Runs with the pending approval filter and count.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["none", "pending", "keyboard"],
    testIds: ["pw.approval-notification"],
  },
  {
    id: "shell.evidence.open-close",
    surface: "Shell",
    control: "Evidence inspector",
    behavior: "Opens and closes by trigger, close button, scrim, and Escape with focus restoration.",
    baseline: "functional-uncovered",
    milestone: "M1",
    states: ["ready", "open", "empty", "resolved", "keyboard", "mobile"],
    testIds: ["pw.evidence-inspector"],
  },
  {
    id: "overview.start-literature",
    surface: "Overview",
    control: "Start a literature review",
    behavior: "Navigates to the Literature Protocol view.",
    baseline: "functional-covered",
    milestone: "M1",
    states: NAVIGATION_STATES,
    testIds: ["pw.literature-open", "jest.literature-open"],
  },
  {
    id: "overview.open-library",
    surface: "Overview",
    control: "Explore evidence library",
    behavior: "Navigates to the Library.",
    baseline: "functional-covered",
    milestone: "M1",
    states: NAVIGATION_STATES,
    testIds: ["pw.operational-surfaces"],
  },
  {
    id: "overview.open-studio-card",
    surface: "Overview",
    control: "Six capability cards",
    behavior: "Each card opens its distinct studio route.",
    baseline: "functional-covered",
    milestone: "M1",
    states: NAVIGATION_STATES,
    testIds: ["pw.distinct-studios", "jest.capability-cards"],
  },
  {
    id: "overview.open-runs",
    surface: "Overview",
    control: "View all runs and run rows",
    behavior: "Opens Runs and selects the chosen run when applicable.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["ready", "empty", "keyboard"],
    testIds: ["pw.overview-runs"],
  },
  {
    id: "literature.protocol.question",
    surface: "Literature",
    control: "Research question",
    behavior: "Edits and validates the protocol question.",
    baseline: "functional-uncovered",
    milestone: "M3",
    states: STANDARD_STATES,
    testIds: ["jest.literature-protocol", "pw.literature-protocol"],
  },
  {
    id: "literature.protocol.date-window",
    surface: "Literature",
    control: "Published from and through",
    behavior: "Edits an ordered bounded date window and surfaces validation errors.",
    baseline: "functional-uncovered",
    milestone: "M3",
    states: STANDARD_STATES,
    testIds: ["jest.literature-date-window", "pw.literature-protocol"],
  },
  {
    id: "literature.protocol.criteria",
    surface: "Literature",
    control: "Include and exclude criteria chips",
    behavior: "Adds and removes protocol criteria and includes them in the run request.",
    baseline: "functional-covered",
    milestone: "M3",
    states: ["ready", "editing", "empty", "duplicate", "error"],
    testIds: ["jest.literature-criteria", "pw.literature-protocol"],
  },
  {
    id: "literature.protocol.sources",
    surface: "Literature",
    control: "Scholarly source checkboxes",
    behavior: "Selects enabled and healthy source connectors included in the request.",
    baseline: "functional-uncovered",
    milestone: "M3",
    states: ["ready", "selected", "disabled", "unhealthy", "unauthorized"],
    testIds: ["jest.literature-sources", "pw.literature-protocol"],
  },
  {
    id: "literature.protocol.online",
    surface: "Literature",
    control: "Online research toggle",
    behavior: "Requires explicit acknowledgement and sends only the public query.",
    baseline: "functional-uncovered",
    milestone: "M3",
    states: ["off", "acknowledgement", "on", "unavailable", "error"],
    testIds: ["jest.literature-online", "pw.literature-online"],
  },
  {
    id: "literature.protocol.run",
    surface: "Literature",
    control: "Search and screen evidence",
    behavior: "Creates a run with loading, partial, success, empty, retry, and error states.",
    baseline: "functional-covered",
    milestone: "M3",
    states: STANDARD_STATES,
    testIds: ["pw.literature-run"],
  },
  {
    id: "literature.screen.tab",
    surface: "Literature",
    control: "Screen tab",
    behavior: "Shows the candidate screening queue with per-record include/exclude/maybe decisions.",
    baseline: "functional-covered",
    milestone: "M3",
    states: ["empty", "loading", "ready", "partial", "error"],
    testIds: ["jest.literature-tabs", "pw.literature-screen"],
  },
  {
    id: "literature.screen.decision",
    surface: "Literature",
    control: "Include, exclude, maybe, reason, and bulk screening actions",
    behavior: "Records a per-item decision in component state and deterministically changes included/excluded/maybe counts and the extraction and audit tabs.",
    baseline: "functional-covered",
    milestone: "M3",
    states: STANDARD_STATES,
    testIds: ["jest.screening-decisions", "pw.literature-screen"],
  },
  {
    id: "literature.extract.tab",
    surface: "Literature",
    control: "Extract tab",
    behavior: "Shows the evidence-linked extraction matrix filtered by current screening decisions.",
    baseline: "functional-covered",
    milestone: "M3",
    states: ["empty", "loading", "ready", "partial", "error"],
    testIds: ["jest.literature-tabs", "pw.literature-extract"],
  },
  {
    id: "literature.extract.edit-export",
    surface: "Literature",
    control: "Extraction schema, cells, and export",
    behavior: "Edits source-linked values and exports the current version.",
    baseline: "functional-covered",
    milestone: "M3",
    states: STANDARD_STATES,
    testIds: ["jest.extraction-matrix", "pw.literature-extract"],
  },
  {
    id: "literature.synthesize.tab",
    surface: "Literature",
    control: "Synthesize tab",
    behavior: "Shows the audited synthesis narrative for the current run.",
    baseline: "functional-covered",
    milestone: "M3",
    states: ["empty", "loading", "ready", "unsupported", "error"],
    testIds: ["jest.literature-tabs", "pw.literature-synthesize"],
  },
  {
    id: "literature.audit.tab",
    surface: "Literature",
    control: "Audit tab",
    behavior: "Shows resolved/unresolved citation status and excluded-record reasons for the current run.",
    baseline: "functional-covered",
    milestone: "M3",
    states: ["empty", "loading", "passed", "warning", "blocked", "error"],
    testIds: ["jest.literature-tabs", "pw.literature-audit"],
  },
  {
    id: "grant.discovery.search",
    surface: "Grant",
    control: "Opportunity discovery query and filters",
    behavior: "Finds net-new opportunities through selected governed connectors.",
    baseline: "functional-covered",
    milestone: "M4",
    states: STANDARD_STATES,
    testIds: ["jest.grant-discovery", "pw.grant-discovery"],
  },
  {
    id: "grant.discovery.sources",
    surface: "Grant",
    control: "Grant source toggles and add connector",
    behavior: "Toggles assigned funding connectors included in the run request and opens a connector-builder dialog that records a draft request pending admin review.",
    baseline: "functional-covered",
    milestone: "M4",
    states: ["ready", "selected", "unhealthy", "unauthorized", "empty", "error"],
    testIds: ["jest.grant-sources", "pw.grant-connectors"],
  },
  {
    id: "grant.opportunity.id",
    surface: "Grant",
    control: "Opportunity ID",
    behavior: "Selects or imports a canonical notice and amendments.",
    baseline: "functional-uncovered",
    milestone: "M4",
    states: STANDARD_STATES,
    testIds: ["jest.grant-opportunity", "pw.grant-opportunity"],
  },
  {
    id: "grant.requirements.open",
    surface: "Grant",
    control: "Requirement matrix rows",
    behavior: "Opens the source evidence and mapping for a requirement.",
    baseline: "functional-covered",
    milestone: "M4",
    states: ["unmapped", "mapped", "needs-input", "blocked"],
    testIds: ["jest.grant-requirements", "pw.grant-requirements"],
  },
  {
    id: "grant.editor.tabs",
    surface: "Grant",
    control: "Specific aims, Significance, and Approach tabs",
    behavior: "Switches section editor content between drafted sections and a not-yet-drafted state.",
    baseline: "functional-covered",
    milestone: "M4",
    states: ["ready", "selected", "dirty", "saving", "saved", "error"],
    testIds: ["jest.grant-editor", "pw.grant-draft"],
  },
  {
    id: "grant.editor.framing",
    surface: "Grant",
    control: "Project framing",
    behavior: "Edits validated project context without inventing institutional facts.",
    baseline: "functional-uncovered",
    milestone: "M4",
    states: STANDARD_STATES,
    testIds: ["jest.grant-framing", "pw.grant-draft"],
  },
  {
    id: "grant.facts.confirm",
    surface: "Grant",
    control: "Core project facts verified",
    behavior: "Records the verifying user and controls deterministic readiness.",
    baseline: "functional-uncovered",
    milestone: "M4",
    states: ["unchecked", "checked", "permission-denied", "error"],
    testIds: ["jest.grant-facts", "pw.grant-fit"],
  },
  {
    id: "grant.package.build",
    surface: "Grant",
    control: "Parse notice and build package",
    behavior: "Runs notice normalization, compliance, and bounded drafting.",
    baseline: "functional-covered",
    milestone: "M4",
    states: STANDARD_STATES,
    testIds: ["pw.grant-build"],
  },
  {
    id: "grant.review.red-team",
    surface: "Grant",
    control: "Red-team draft",
    behavior: "Runs a distinct red-team studio pass and shows the resulting readiness, gaps, and blockers.",
    baseline: "functional-covered",
    milestone: "M4",
    states: ["ready", "running", "findings", "resolved", "error"],
    testIds: ["jest.grant-red-team", "pw.grant-review"],
  },
  {
    id: "matching.need.query",
    surface: "Matching",
    control: "Expertise, method, or need",
    behavior: "Edits the typed matching need.",
    baseline: "functional-uncovered",
    milestone: "M5",
    states: STANDARD_STATES,
    testIds: ["jest.matching-need", "pw.matching-need"],
  },
  {
    id: "matching.need.entity-types",
    surface: "Matching",
    control: "Record type checkboxes",
    behavior: "Sends selected record kinds as part of the run request inputs.",
    baseline: "functional-covered",
    milestone: "M5",
    states: ["selected", "unselected", "empty", "disabled"],
    testIds: ["jest.matching-types", "pw.matching-filters"],
  },
  {
    id: "matching.need.hard-filters",
    surface: "Matching",
    control: "Hard filter checkboxes",
    behavior: "Sends selected hard filter ids as part of the run request inputs.",
    baseline: "functional-covered",
    milestone: "M5",
    states: ["selected", "unselected", "no-results", "error"],
    testIds: ["jest.matching-hard-filters", "pw.matching-filters"],
  },
  {
    id: "matching.need.sources",
    surface: "Matching",
    control: "Public, institutional, and Work IQ sources",
    behavior: "Selects governed sources with consent/readiness constraints.",
    baseline: "functional-covered",
    milestone: "M5",
    states: ["ready", "selected", "unavailable", "consent-required", "error"],
    testIds: ["jest.matching-sources", "pw.matching-sources"],
  },
  {
    id: "matching.run",
    surface: "Matching",
    control: "Build verified shortlist",
    behavior: "Generates, resolves, hard-filters, and deterministically scores candidates.",
    baseline: "functional-covered",
    milestone: "M5",
    states: STANDARD_STATES,
    testIds: ["pw.matching-run"],
  },
  {
    id: "matching.result.select",
    surface: "Matching",
    control: "Candidate cards",
    behavior: "Selects a candidate and shows exact score/evidence details.",
    baseline: "functional-uncovered",
    milestone: "M5",
    states: ["ready", "selected", "keyboard", "stale", "conflict"],
    testIds: ["jest.matching-select", "pw.matching-results"],
  },
  {
    id: "matching.compare-shortlist",
    surface: "Matching",
    control: "Compare and shortlist actions",
    behavior: "Toggles shortlist membership per candidate in component state and shows a transparent side-by-side score comparison.",
    baseline: "functional-covered",
    milestone: "M5",
    states: STANDARD_STATES,
    testIds: ["jest.matching-shortlist", "pw.matching-shortlist"],
  },
  {
    id: "dataset.upload",
    surface: "Dataset",
    control: "Dataset upload",
    behavior: "Validates a bounded CSV/JSON file client-side, then uploads real bytes through the Library upload API.",
    baseline: "functional-covered",
    milestone: "M6",
    states: ["empty", "uploading", "quarantined", "validated", "rejected", "error"],
    testIds: ["jest.dataset-upload", "pw.dataset-upload"],
  },
  {
    id: "dataset.asset.select",
    surface: "Dataset",
    control: "Dataset asset cards",
    behavior: "Selects an authorized uploaded asset and updates the request.",
    baseline: "functional-uncovered",
    milestone: "M6",
    states: ["ready", "selected", "processing", "rejected", "unauthorized"],
    testIds: ["jest.dataset-assets", "pw.dataset-assets"],
  },
  {
    id: "dataset.objective",
    surface: "Dataset",
    control: "Analysis objective",
    behavior: "Edits a bounded analysis objective.",
    baseline: "functional-uncovered",
    milestone: "M6",
    states: STANDARD_STATES,
    testIds: ["jest.dataset-objective", "pw.dataset-plan"],
  },
  {
    id: "dataset.profile",
    surface: "Dataset",
    control: "Analyze with Foundry Code Interpreter",
    behavior: "Profiles uploaded bytes, invokes the Foundry Dataset Agent Toolbox, and produces schema/quality findings plus bounded analysis.",
    baseline: "functional-covered",
    milestone: "M6",
    states: STANDARD_STATES,
    testIds: ["pw.dataset-profile"],
  },
  {
    id: "dataset.plan.approve",
    surface: "Dataset",
    control: "Edit and approve analysis plan",
    behavior: "Requires explicit approval before the bounded dataset is sent to the project-scoped Foundry Code Interpreter.",
    baseline: "functional-covered",
    milestone: "M6",
    states: ["draft", "dirty", "waiting-for-approval", "approved", "rejected", "error"],
    testIds: ["jest.dataset-plan", "pw.dataset-plan"],
  },
  {
    id: "dataset.execution",
    surface: "Dataset",
    control: "Approve and invoke Foundry Code Interpreter analysis",
    behavior: "Sends only the bounded approved dataset to the Foundry Hosted Dataset Agent and its project-scoped Code Interpreter Toolbox, then renders typed outputs and limitations.",
    baseline: "functional-covered",
    milestone: "M6",
    states: ["pending-approval", "running", "completed", "failed", "blocked"],
    testIds: ["jest.dataset-plan", "pw.dataset-upload"],
  },
  {
    id: "institutional.corpora",
    surface: "Institutional",
    control: "Authorized corpus checkboxes",
    behavior: "Sends selected authorized corpora as part of the run request and keeps the legal-hold corpus locked.",
    baseline: "functional-covered",
    milestone: "M7",
    states: ["selected", "unselected", "locked", "empty", "error"],
    testIds: ["jest.institutional-corpora", "pw.institutional-corpora"],
  },
  {
    id: "institutional.work-iq",
    surface: "Institutional",
    control: "Work IQ readiness and consent",
    behavior: "Shows an honest, disabled, default-off readiness panel; this workspace never claims Work IQ is configured or enabled.",
    baseline: "functional-covered",
    milestone: "M7",
    states: ["unconfigured", "admin-consent-required", "user-consent-required", "ready", "unsupported-network"],
    testIds: ["jest.work-iq-readiness", "pw.work-iq-readiness"],
  },
  {
    id: "institutional.question",
    surface: "Institutional",
    control: "Institutional question",
    behavior: "Edits and submits a scoped question.",
    baseline: "functional-covered",
    milestone: "M7",
    states: STANDARD_STATES,
    testIds: ["pw.institutional-answer"],
  },
  {
    id: "institutional.evidence.open",
    surface: "Institutional",
    control: "Inline citation buttons",
    behavior: "Opens a dialog with the exact citation title, section, page, quote, checksum, and license.",
    baseline: "functional-covered",
    milestone: "M7",
    states: ["ready", "open", "unavailable", "superseded", "permission-denied"],
    testIds: ["jest.institutional-evidence", "pw.institutional-evidence"],
  },
  {
    id: "workflow.template",
    surface: "Workflow",
    control: "Workflow template cards",
    behavior: "Selects and loads an editable versioned graph.",
    baseline: "functional-uncovered",
    milestone: "M8",
    states: ["ready", "selected", "loading", "error"],
    testIds: ["jest.workflow-template", "pw.workflow-template"],
  },
  {
    id: "workflow.trigger",
    surface: "Workflow",
    control: "Trigger selector",
    behavior: "Configures a typed manual, schedule, webhook, GitHub, or library trigger.",
    baseline: "functional-uncovered",
    milestone: "M8",
    states: STANDARD_STATES,
    testIds: ["jest.workflow-trigger", "pw.workflow-trigger"],
  },
  {
    id: "workflow.catalog",
    surface: "Workflow",
    control: "Agent, tool, and studio catalog",
    behavior: "Adds only authorized versioned capabilities to the graph.",
    baseline: "functional-covered",
    milestone: "M8",
    states: ["loading", "ready", "empty", "unauthorized", "preview", "error"],
    testIds: ["jest.workflow-catalog", "pw.workflow-catalog"],
  },
  {
    id: "workflow.graph.edit",
    surface: "Workflow",
    control: "Add, remove, and configure a bounded step list",
    behavior: "Adds up to 8 typed steps, blocks removing a step that others depend on, and edits label/kind/retries/dependencies/approval in an accessible list editor; edited steps are sent to dry run.",
    baseline: "functional-covered",
    milestone: "M8",
    states: ["draft", "dirty", "invalid", "valid", "saving", "error"],
    testIds: ["jest.workflow-graph", "pw.workflow-graph"],
  },
  {
    id: "workflow.canvas.zoom",
    surface: "Workflow",
    control: "Zoom out and zoom in",
    behavior: "Changes the graph viewport scale between 50% and 150% without changing workflow semantics.",
    baseline: "functional-covered",
    milestone: "M8",
    states: ["ready", "minimum", "maximum", "keyboard"],
    testIds: ["pw.workflow-viewport"],
  },
  {
    id: "workflow.validate",
    surface: "Workflow",
    control: "Validate and dry run",
    behavior: "Compiles and dry-runs with external side effects disabled.",
    baseline: "functional-covered",
    milestone: "M8",
    states: ["draft", "validating", "passed", "blocked", "error"],
    testIds: ["pw.workflow-dry-run"],
  },
  {
    id: "workflow.activate",
    surface: "Workflow",
    control: "Activate after approval",
    behavior: "Stays disabled until a dry run passes with zero graph errors, then requires an explicit confirmation dialog before recording a session-local activation state.",
    baseline: "functional-covered",
    milestone: "M8",
    states: ["disabled", "ready", "waiting-for-approval", "active", "rejected", "error"],
    testIds: ["jest.workflow-activation", "pw.workflow-activation"],
  },
  {
    id: "workflow.run.manage",
    surface: "Workflow",
    control: "Pause, resume, retry, cancel, inspect, clone, and version",
    behavior: "Manages durable runs without repeating completed external effects.",
    baseline: "functional-covered",
    milestone: "M8",
    states: ["running", "paused", "failed", "retrying", "cancelled", "completed"],
    testIds: ["jest.workflow-run", "pw.workflow-run"],
  },
  {
    id: "library.search-filter",
    surface: "Library",
    control: "Search and type filters",
    behavior: "Filters real persisted library records with no-result handling.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["ready", "filtered", "empty", "keyboard"],
    testIds: ["jest.library-filter", "pw.library-filter"],
  },
  {
    id: "library.ingest.open-close",
    surface: "Library",
    control: "Ingest source, close, cancel, and Escape",
    behavior: "Opens/closes an accessible upload dialog with focus restoration.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["closed", "open", "keyboard"],
    testIds: ["jest.library-dialog", "pw.library-ingest"],
  },
  {
    id: "library.ingest.form",
    surface: "Library",
    control: "Title, type, access, file, license, provider, year, and description",
    behavior: "Validates bounded ingestion metadata and real uploaded bytes.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["empty", "invalid", "valid", "submitting", "success", "error"],
    testIds: ["pw.library-ingest", "pw.library-oversize"],
  },
  {
    id: "library.item.open",
    surface: "Library",
    control: "Library item row",
    behavior: "Opens a detail dialog with source metadata, governance, checksum, and evidence counts.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["ready", "processing", "failed", "quarantined", "superseded", "archived"],
    testIds: ["jest.library-detail", "pw.library-detail"],
  },
  {
    id: "runs.filter",
    surface: "Runs",
    control: "Run status filters",
    behavior: "Filters runs and preserves a valid selected run.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["all", "filtered", "empty", "keyboard"],
    testIds: ["jest.runs-filter", "pw.runs-filter"],
  },
  {
    id: "runs.select",
    surface: "Runs",
    control: "Run rows",
    behavior: "Selects a run and displays authoritative events, artifacts, costs, and traces.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["ready", "selected", "loading", "partial", "error"],
    testIds: ["pw.operational-surfaces", "pw.run-detail"],
  },
  {
    id: "approvals.rationale",
    surface: "Approvals",
    control: "Reviewer rationale",
    behavior: "Requires a bounded rationale before a decision.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["empty", "valid", "invalid", "disabled"],
    testIds: ["jest.approval-rationale", "pw.approval-decision"],
  },
  {
    id: "approvals.decide",
    surface: "Approvals",
    control: "Approve, reject, and request changes",
    behavior: "Records actor, exact payload digest, rationale, delivery, and idempotent decision.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["pending", "submitting", "approved", "rejected", "changes-requested", "expired", "error"],
    testIds: ["jest.approval-decision", "pw.approval-decision"],
  },
  {
    id: "settings.tabs",
    surface: "Settings",
    control: "Settings section navigation",
    behavior: "Opens every URL-addressable settings section without blank panels.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: NAVIGATION_STATES,
    testIds: ["jest.settings-tabs", "pw.settings-tabs"],
  },
  {
    id: "settings.general.form",
    surface: "Settings",
    control: "Project profile fields and save",
    behavior: "Validates, persists, and reports success/error without enabling global web research.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: STANDARD_STATES,
    testIds: ["jest.settings-general", "pw.settings-general"],
  },
  {
    id: "settings.connectors.search-filter",
    surface: "Settings",
    control: "Connector search and category filters",
    behavior: "Filters persisted connectors and handles no results.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["ready", "filtered", "empty", "keyboard"],
    testIds: ["jest.connector-filter", "pw.connector-filter"],
  },
  {
    id: "settings.connectors.enable",
    surface: "Settings",
    control: "Enable connector",
    behavior: "Uses the connector manager widget to enable or disable optional connectors while protecting required dependencies.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["enabled", "disabled", "locked", "saving", "error"],
    testIds: ["jest.connector-enable", "pw.connector-enable"],
  },
  {
    id: "settings.connectors.assign",
    surface: "Settings",
    control: "Assigned specialist checkboxes",
    behavior: "Uses the connector manager widget to persist allowlisted specialist assignments and prevent invalid combinations.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["selected", "unselected", "saving", "invalid", "error"],
    testIds: ["jest.connector-assign", "pw.connector-assign"],
  },
  {
    id: "settings.connectors.terms",
    surface: "Settings",
    control: "Connector terms link",
    behavior: "Opens an allowlisted HTTPS terms URL safely.",
    baseline: "functional-uncovered",
    milestone: "M9",
    states: ["ready", "blocked-url"],
    testIds: ["jest.connector-terms", "pw.connector-terms"],
  },
  {
    id: "settings.connectors.test",
    surface: "Settings",
    control: "Test connection",
    behavior: "Runs a bounded audited test, updates health/freshness, and distinguishes missing gateway setup from a provider outage.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["ready", "testing", "configuration-required", "healthy", "degraded", "failed"],
    testIds: ["pw.operational-surfaces", "pw.connector-test"],
  },
  {
    id: "settings.connectors.versions",
    surface: "Settings",
    control: "APIM, MCP, and Toolbox version promotion and rollback",
    behavior: "Shows immutable versions and requires approval before default promotion.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["draft", "validating", "canary", "active", "deprecated", "failed"],
    testIds: ["jest.connector-versions", "pw.connector-versions"],
  },
  {
    id: "settings.integrations.readiness",
    surface: "Settings",
    control: "APIM/Toolbox, Work IQ, GitHub Copilot connector authoring, and Foundry Code Interpreter readiness",
    behavior: "Shows deployment-managed connector/toolbox state, scoped draft-PR connector authoring, the project-scoped Code Interpreter boundary, and truthful disabled Work IQ prerequisites.",
    baseline: "functional-covered",
    milestone: "M9",
    states: ["unconfigured", "partial", "ready", "permission-denied", "unsupported", "error"],
    testIds: ["jest.integration-readiness", "pw.integration-readiness"],
  },
] as const;

export const INTERACTION_GAPS = INTERACTION_MANIFEST.filter(
  (item) => item.baseline === "unwired" || item.baseline === "missing",
);

const ALL_VIEWPORTS = ["desktop", "tablet", "mobile"] as const;

export const CORE_SCREENSHOT_CONTRACTS = [
  {
    id: "visual.core.overview",
    route: "/",
    heading: "Move from question to defensible evidence.",
  },
  {
    id: "visual.core.literature",
    route: "/?view=literature",
    heading: "Literature Studio",
  },
  {
    id: "visual.core.grant",
    route: "/?view=grant",
    heading: "Grant Studio",
  },
  {
    id: "visual.core.matching",
    route: "/?view=matching",
    heading: "Matching Explorer",
  },
  {
    id: "visual.core.dataset",
    route: "/?view=dataset",
    heading: "Dataset Lab",
  },
  {
    id: "visual.core.institutional",
    route: "/?view=institutional_qa",
    heading: "Institutional Q&A",
  },
  {
    id: "visual.core.workflow",
    route: "/?view=orchestration",
    heading: "Workflow Automation",
  },
  {
    id: "visual.core.library",
    route: "/?view=library",
    heading: "Library",
  },
  {
    id: "visual.core.runs",
    route: "/?view=runs",
    heading: "Runs & Approvals",
  },
  {
    id: "visual.core.settings",
    route: "/?view=settings",
    heading: "Project Settings",
  },
] as const;

export const STATE_SCREENSHOT_IDS = [
  "visual.state.empty",
  "visual.state.loading",
  "visual.state.error",
  "visual.state.authorization",
] as const;

const SURFACE_ROUTES: Readonly<Record<string, string>> = {
  Approvals: "/?view=runs",
  Dataset: "/?view=dataset",
  Grant: "/?view=grant",
  Institutional: "/?view=institutional_qa",
  Library: "/?view=library",
  Literature: "/?view=literature",
  Matching: "/?view=matching",
  Overview: "/",
  Runs: "/?view=runs",
  Settings: "/?view=settings",
  Shell: "/",
  Workflow: "/?view=orchestration",
};

const SURFACE_SCREENSHOTS: Readonly<Record<string, readonly string[]>> = {
  Approvals: ["visual.core.runs"],
  Dataset: ["visual.core.dataset"],
  Grant: ["visual.core.grant"],
  Institutional: [
    "visual.core.institutional",
    "visual.state.authorization",
  ],
  Library: ["visual.core.library"],
  Literature: [
    "visual.core.literature",
    "visual.state.empty",
    "visual.state.loading",
    "visual.state.error",
  ],
  Matching: ["visual.core.matching"],
  Overview: ["visual.core.overview"],
  Runs: ["visual.core.runs"],
  Settings: ["visual.core.settings"],
  Shell: ["visual.core.overview"],
  Workflow: ["visual.core.workflow"],
};

export const DECLARED_SCREENSHOT_IDS: ReadonlySet<string> = new Set([
  ...CORE_SCREENSHOT_CONTRACTS.map((contract) => contract.id),
  ...STATE_SCREENSHOT_IDS,
]);

const ASYNC_STATES = new Set([
  "loading",
  "running",
  "retrying",
  "saving",
  "submitting",
  "testing",
  "uploading",
  "validating",
]);
const EMPTY_STATES = new Set(["empty", "none", "no-results"]);
const ERROR_STATES = new Set([
  "blocked",
  "error",
  "failed",
  "invalid",
  "rejected",
  "unavailable",
]);
const AUTH_STATES = new Set([
  "admin-consent-required",
  "consent-required",
  "locked",
  "permission-denied",
  "unauthorized",
  "user-consent-required",
]);

function classifyState(name: string): CoverageStateKind {
  if (ASYNC_STATES.has(name)) return "async";
  if (EMPTY_STATES.has(name)) return "empty";
  if (ERROR_STATES.has(name)) return "error";
  if (AUTH_STATES.has(name)) return "auth";
  return "behavior";
}

export const UI_COVERAGE_MANIFEST: readonly UiCoverageContract[] =
  INTERACTION_MANIFEST.map((interaction) => ({
    ...interaction,
    route: SURFACE_ROUTES[interaction.surface],
    viewports: ALL_VIEWPORTS,
    rtlTestIds: interaction.testIds.filter((id) => id.startsWith("jest.")),
    playwrightTestIds: interaction.testIds.filter((id) => id.startsWith("pw.")),
    playwrightStateTestIds: interaction.states.map((state) => ({
      state,
      testIds: interaction.testIds.filter((id) => id.startsWith("pw.")),
    })),
    screenshotIds: SURFACE_SCREENSHOTS[interaction.surface],
    classifiedStates: interaction.states.map((name) => ({
      name,
      kind: classifyState(name),
    })),
  }));
