/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approvals */
        get: operations["approvals_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_approvals__approval_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invoke Assistant */
        post: operations["invoke_assistant_api_assistant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connectors */
        get: operations["connectors_api_connectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/{connector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Connector */
        put: operations["update_connector_api_connectors__connector_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/{connector_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connector */
        post: operations["test_connector_api_connectors__connector_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Dataset */
        post: operations["execute_dataset_api_datasets_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Dataset */
        post: operations["plan_dataset_api_datasets_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Library Item */
        post: operations["ingest_library_item_api_library_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Library Item */
        post: operations["upload_library_item_api_library_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{capability}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Capability */
        post: operations["run_capability_api_research__capability__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Settings */
        get: operations["project_settings_api_settings_get"];
        /** Update Project Settings */
        put: operations["update_project_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studios/{capability}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Studio */
        post: operations["run_studio_api_studios__capability__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflows */
        get: operations["workflows_api_workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentInsight */
        AgentInsight: {
            /** Agent Name */
            agent_name: string;
            /** Content */
            content: string;
            evidence_state: components["schemas"]["EvidenceState"];
            /**
             * Online Research Used
             * @default false
             */
            online_research_used: boolean;
            /** Referenced Source Ids */
            referenced_source_ids?: string[];
            /** Unresolved Source Ids */
            unresolved_source_ids?: string[];
        };
        /** AgentSetting */
        AgentSetting: {
            /** Deployment */
            deployment: string;
            /** Id */
            id: string;
            /** Model Tier */
            model_tier: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Web Access */
            web_access: string;
            /** Workflow Steps */
            workflow_steps: string[];
        };
        /** AnalysisStep */
        AnalysisStep: {
            /** Deterministic */
            deterministic: boolean;
            /** Id */
            id: string;
            /** Method */
            method: string;
            /** Question */
            question: string;
            /** Status */
            status: string;
        };
        /** ApprovalDecision */
        ApprovalDecision: {
            decision: components["schemas"]["ApprovalState"];
            /** Rationale */
            rationale: string;
        };
        /** ApprovalRecord */
        ApprovalRecord: {
            /** Approver Id */
            approver_id?: string | null;
            /** Approver Name */
            approver_name?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Decision Event Id */
            decision_event_id?: string | null;
            /** Destination */
            destination: string;
            /**
             * Event Delivery
             * @default not_requested
             */
            event_delivery: string;
            /** Evidence Summary */
            evidence_summary: string;
            /** Gated Action */
            gated_action: string;
            /** Id */
            id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Rationale */
            rationale?: string | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Requested By */
            requested_by: string;
            /** Risk */
            risk: string;
            /** Run Id */
            run_id: string;
            state: components["schemas"]["ApprovalState"];
            /** Title */
            title: string;
        };
        /**
         * ApprovalState
         * @enum {string}
         */
        ApprovalState: "pending" | "approved" | "rejected" | "cancelled";
        /** ArtifactSection */
        ArtifactSection: {
            /** Body */
            body: string;
            /** Citation Ids */
            citation_ids?: string[];
            /** Heading */
            heading: string;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
        };
        /** AssistantRequest */
        AssistantRequest: {
            capability?: components["schemas"]["Capability"] | null;
            /** Message */
            message: string;
        };
        /** AssistantResponse */
        AssistantResponse: {
            /** Agent Name */
            agent_name: string;
            /** Content */
            content: string;
            /** Mode */
            mode: string;
            /** Response Id */
            response_id?: string | null;
        };
        /** AutomationStep */
        AutomationStep: {
            /** Approval Required */
            approval_required: boolean;
            /** Depends On */
            depends_on: string[];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "activity" | "fan_out" | "agent" | "approval" | "external_action";
            /** Label */
            label: string;
            /** Retry Limit */
            retry_limit: number;
        };
        /** AutomationStudioResult */
        AutomationStudioResult: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Dry Run Status */
            dry_run_status: string;
            /** Graph Hash */
            graph_hash: string;
            /** Graph Version */
            graph_version: string;
            insight?: components["schemas"]["AgentInsight"] | null;
            run: components["schemas"]["StudioRun"];
            /** Steps */
            steps: components["schemas"]["AutomationStep"][];
            /** Template Id */
            template_id: string;
            /** Trigger */
            trigger: string;
            /** Validation Errors */
            validation_errors: string[];
        };
        /** Body_upload_library_item_api_library_upload_post */
        Body_upload_library_item_api_library_upload_post: {
            /**
             * Access
             * @default internal
             * @enum {string}
             */
            access: "public" | "internal" | "restricted";
            /** Description */
            description: string;
            /** File */
            file: string;
            /** Kind */
            kind: string;
            /** License */
            license: string;
            /** Publication Year */
            publication_year?: number | null;
            /**
             * Source
             * @default Workspace upload
             */
            source: string;
            /** Title */
            title: string;
        };
        /**
         * Capability
         * @enum {string}
         */
        Capability: "literature" | "grant" | "matching" | "dataset" | "institutional_qa" | "orchestration";
        /** CapabilitySpec */
        CapabilitySpec: {
            /** Accent */
            accent: string;
            /** Description */
            description: string;
            /** Example Prompt */
            example_prompt: string;
            id: components["schemas"]["Capability"];
            /** Short Title */
            short_title: string;
            /** Title */
            title: string;
        };
        /** Citation */
        Citation: {
            /** Canonical Url */
            canonical_url?: string | null;
            /** Checksum */
            checksum: string;
            /** Chunk Id */
            chunk_id: string;
            /** Id */
            id: string;
            /** Identifier */
            identifier?: string | null;
            /** License */
            license: string;
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            /** Quote */
            quote: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at?: string;
            /** Section */
            section: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
        };
        /** ComputeProposal */
        ComputeProposal: {
            /** Adapter */
            adapter: string;
            /** Approval Required */
            approval_required: boolean;
            /** Estimated Bytes */
            estimated_bytes: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Estimated Minutes */
            estimated_minutes: number | null;
            /** Stages */
            stages: string[];
        };
        /** ConnectorSetting */
        ConnectorSetting: {
            /** Assigned Agents */
            assigned_agents: string[];
            /** Auth Kind */
            auth_kind: string;
            /** Capabilities */
            capabilities: string[];
            /** Category */
            category: string;
            /** Data Boundary */
            data_boundary: string;
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Last Tested At */
            last_tested_at?: string | null;
            /** Name */
            name: string;
            /** Secret Status */
            secret_status: string;
            /**
             * Terms Url
             * Format: uri
             */
            terms_url: string;
            /** Test Status */
            test_status: string;
        };
        /** ConnectorUpdate */
        ConnectorUpdate: {
            /** Assigned Agents */
            assigned_agents: string[];
            /** Enabled */
            enabled: boolean;
        };
        /** CopilotPlanRequest */
        CopilotPlanRequest: {
            /** Objective */
            objective: string;
            /**
             * Schema Summary
             * @default
             */
            schema_summary: string;
        };
        /** CopilotPlanResponse */
        CopilotPlanResponse: {
            /**
             * Executed
             * @default false
             */
            executed: boolean;
            /** Plan */
            plan: string;
        };
        /** DatasetExecutionRequest */
        DatasetExecutionRequest: {
            /**
             * Analysis Code
             * @default summary = df.describe(include='all').fillna('').to_dict()
             *     print(summary)
             */
            analysis_code: string;
            /** Approval Acknowledged */
            approval_acknowledged: boolean;
            /** Csv Text */
            csv_text: string;
            /** Filename */
            filename: string;
        };
        /** DatasetExecutionResult */
        DatasetExecutionResult: {
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** DatasetFieldProfile */
        DatasetFieldProfile: {
            /** Data Type */
            data_type: string;
            /** Missing */
            missing: number;
            /** Name */
            name: string;
            /** Range Or Values */
            range_or_values: string;
            /** Unique */
            unique: number;
        };
        /** DatasetStudioResult */
        DatasetStudioResult: {
            /** Analysis Plan */
            analysis_plan: components["schemas"]["AnalysisStep"][];
            /** Asset Name */
            asset_name: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Column Count */
            column_count: number;
            compute_proposal: components["schemas"]["ComputeProposal"];
            /** Fields */
            fields: components["schemas"]["DatasetFieldProfile"][];
            insight?: components["schemas"]["AgentInsight"] | null;
            /** Interpretation */
            interpretation: string[];
            /** Profile Note */
            profile_note: string;
            /** Profile Status */
            profile_status: string;
            /** Quality Findings */
            quality_findings: string[];
            /** Row Count */
            row_count: number;
            run: components["schemas"]["StudioRun"];
        };
        /** DraftSection */
        DraftSection: {
            /** Body */
            body: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Word Count */
            word_count: number;
        };
        /** EvidenceExtraction */
        EvidenceExtraction: {
            /** Citation Ids */
            citation_ids: string[];
            /** Limitation */
            limitation: string;
            /** Method */
            method: string;
            /** Outcome */
            outcome: string;
            /** Population */
            population: string;
            /** Source Id */
            source_id: string;
        };
        /**
         * EvidenceState
         * @enum {string}
         */
        EvidenceState: "verified" | "model_analysis" | "unsupported" | "blocked";
        /** GrantOpportunity */
        GrantOpportunity: {
            /** Canonical Url */
            canonical_url: string;
            /** Deadline */
            deadline: string;
            /** Identifier */
            identifier: string;
            /** Sponsor */
            sponsor: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** GrantRequirement */
        GrantRequirement: {
            /** Category */
            category: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Text */
            text: string;
        };
        /** GrantStudioResult */
        GrantStudioResult: {
            /** Blockers */
            blockers: string[];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Fact Gaps */
            fact_gaps: components["schemas"]["ProjectFactGap"][];
            insight?: components["schemas"]["AgentInsight"] | null;
            opportunity: components["schemas"]["GrantOpportunity"];
            /** Readiness */
            readiness: number;
            /** Requirements */
            requirements: components["schemas"]["GrantRequirement"][];
            run: components["schemas"]["StudioRun"];
            /** Sections */
            sections: components["schemas"]["DraftSection"][];
            /** Specific Aims */
            specific_aims: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Mode */
            mode: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** InstitutionalStudioResult */
        InstitutionalStudioResult: {
            /** Abstained */
            abstained: boolean;
            /** Answer */
            answer: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Conflicts */
            conflicts: components["schemas"]["PolicyConflict"][];
            /** Escalation */
            escalation?: string | null;
            insight?: components["schemas"]["AgentInsight"] | null;
            run: components["schemas"]["StudioRun"];
            /** Scope */
            scope: string;
            /** Versions */
            versions: components["schemas"]["PolicyVersion"][];
        };
        /** LibraryIngestRequest */
        LibraryIngestRequest: {
            /**
             * Access
             * @default internal
             * @enum {string}
             */
            access: "public" | "internal" | "restricted";
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /** License */
            license: string;
            /** Publication Year */
            publication_year?: number | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** LibraryIngestResponse */
        LibraryIngestResponse: {
            item: components["schemas"]["LibraryItem"];
            run: components["schemas"]["RunSummary"];
        };
        /** LibraryItem */
        LibraryItem: {
            /** Access */
            access: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Blob Uri */
            blob_uri?: string | null;
            /** Checksum */
            checksum: string;
            /** Connector */
            connector: string;
            /** Content Type */
            content_type?: string | null;
            /** Description */
            description: string;
            /** Evidence Count */
            evidence_count: number;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** License */
            license: string;
            /** Provider */
            provider: string;
            /** Publication Year */
            publication_year?: number | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Source */
            source: string;
            status: components["schemas"]["LibraryStatus"];
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /**
         * LibraryStatus
         * @enum {string}
         */
        LibraryStatus: "ready" | "processing" | "needs_review" | "blocked";
        /** LiteratureStudioResult */
        LiteratureStudioResult: {
            /** Candidate Count */
            candidate_count: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Extraction Matrix */
            extraction_matrix: components["schemas"]["EvidenceExtraction"][];
            insight?: components["schemas"]["AgentInsight"] | null;
            protocol: components["schemas"]["ReviewProtocol"];
            run: components["schemas"]["StudioRun"];
            /** Screening */
            screening: components["schemas"]["ScreeningDecision"][];
            /** Search Queries */
            search_queries: string[];
            /** Synthesis */
            synthesis: string[];
        };
        /** MatchCriterion */
        MatchCriterion: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Weight */
            weight: number;
        };
        /** MatchItem */
        MatchItem: {
            /** Citation Ids */
            citation_ids: string[];
            /** Freshness */
            freshness: string;
            /** Id */
            id: string;
            kind: components["schemas"]["SourceKind"];
            /** Name */
            name: string;
            /** Rationale */
            rationale: string;
            /** Score */
            score: number;
            /** Score Factors */
            score_factors?: components["schemas"]["MatchScoreFactor"][];
            /** Tags */
            tags?: string[];
        };
        /** MatchScoreFactor */
        MatchScoreFactor: {
            /** Contribution */
            contribution: number;
            /** Evidence Id */
            evidence_id: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Match */
            match: number;
            /** Weight */
            weight: number;
        };
        /** MatchingStudioResult */
        MatchingStudioResult: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Criteria */
            criteria: components["schemas"]["MatchCriterion"][];
            insight?: components["schemas"]["AgentInsight"] | null;
            /** Matches */
            matches: components["schemas"]["RankedEntity"][];
            run: components["schemas"]["StudioRun"];
            /** Shortlist Ids */
            shortlist_ids: string[];
        };
        /** Metric */
        Metric: {
            /** Detail */
            detail?: string | null;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** PolicyConflict */
        PolicyConflict: {
            /** Description */
            description: string;
            /** Severity */
            severity: string;
            /** Source A */
            source_a: string;
            /** Source B */
            source_b: string;
            /** Topic */
            topic: string;
        };
        /** PolicyVersion */
        PolicyVersion: {
            /** Effective Date */
            effective_date: string;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** ProjectFactGap */
        ProjectFactGap: {
            /** Guidance */
            guidance: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
        };
        /** ProjectSettings */
        ProjectSettings: {
            /** Allowed Export Destinations */
            allowed_export_destinations: string[];
            /** Citation Coverage Threshold */
            citation_coverage_threshold: number;
            /** Default Classification */
            default_classification: string;
            /** Description */
            description: string;
            /** Evaluation Policy */
            evaluation_policy: string;
            /** Model Profile */
            model_profile: string;
            /** Name */
            name: string;
            /**
             * Online Research Default
             * @default false
             */
            online_research_default: boolean;
            /** Project Id */
            project_id: string;
            /** Require Human Approval */
            require_human_approval: boolean;
            /** Retention Days */
            retention_days: number;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Active Runs */
            active_runs: number;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Count */
            source_count: number;
        };
        /** ProvenanceManifest */
        ProvenanceManifest: {
            capability: components["schemas"]["Capability"];
            /** Caveats */
            caveats?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Mode */
            mode: string;
            /** Model Deployment */
            model_deployment: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default research-assistant.provenance.v1
             */
            schema_version: string;
            /** Source Checksums */
            source_checksums: {
                [key: string]: string;
            };
            /** Source Ids */
            source_ids: string[];
            /** Verification */
            verification: string;
        };
        /** RankedEntity */
        RankedEntity: {
            /** Components */
            components: components["schemas"]["ScoreComponent"][];
            /** Freshness */
            freshness: string;
            /** Gaps */
            gaps: string[];
            /** Hard Filters Passed */
            hard_filters_passed: boolean;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Strengths */
            strengths: string[];
        };
        /** ResearchRequest */
        ResearchRequest: {
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Group Ids */
            group_ids?: string[];
            /**
             * Project Id
             * @default demo-project
             */
            project_id: string;
            /** Query */
            query: string;
            /**
             * Tenant Id
             * @default demo
             */
            tenant_id: string;
        };
        /** ResearchResult */
        ResearchResult: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Eyebrow */
            eyebrow: string;
            /** Matches */
            matches?: components["schemas"]["MatchItem"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics?: components["schemas"]["Metric"][];
            provenance: components["schemas"]["ProvenanceManifest"];
            run: components["schemas"]["RunRecord"];
            /** Sections */
            sections: components["schemas"]["ArtifactSection"][];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ReviewProtocol */
        ReviewProtocol: {
            /** Date From */
            date_from: number;
            /** Date To */
            date_to: number;
            /** Exclusion Criteria */
            exclusion_criteria: string[];
            /** Inclusion Criteria */
            inclusion_criteria: string[];
            /** Research Question */
            research_question: string;
            /** Sources */
            sources: string[];
        };
        /** RunRecord */
        RunRecord: {
            capability: components["schemas"]["Capability"];
            /** Completed At */
            completed_at?: string | null;
            /** Current Step */
            current_step: string;
            /** Id */
            id: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Project Id */
            project_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            status: components["schemas"]["RunStatus"];
            /** Steps */
            steps?: string[];
            /** Tenant Id */
            tenant_id: string;
            /** Title */
            title: string;
        };
        /** RunStage */
        RunStage: {
            /** Completed At */
            completed_at?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Owner */
            owner: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "planned" | "running" | "waiting_for_approval" | "partial" | "blocked" | "completed" | "cancelled" | "failed";
        /** RunSummary */
        RunSummary: {
            /** Approval Id */
            approval_id?: string | null;
            /**
             * Artifact Count
             * @default 0
             */
            artifact_count: number;
            capability: components["schemas"]["Capability"];
            /** Completed At */
            completed_at?: string | null;
            /** Current Stage */
            current_stage: string;
            /** Durable Instance Id */
            durable_instance_id: string;
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /** Id */
            id: string;
            /** Orchestration Input */
            orchestration_input?: {
                [key: string]: unknown;
            } | null;
            /** Owner */
            owner: string;
            /** Progress */
            progress: number;
            /** Project Id */
            project_id: string;
            /**
             * Scheduler Managed
             * @default false
             */
            scheduler_managed: boolean;
            /**
             * Scheduling State
             * @default not_managed
             */
            scheduling_state: string;
            /** Stages */
            stages?: components["schemas"]["RunStage"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /** Title */
            title: string;
        };
        /** ScoreComponent */
        ScoreComponent: {
            /** Contribution */
            contribution: number;
            /** Criterion Id */
            criterion_id: string;
            /** Evidence Id */
            evidence_id: string;
            /** Label */
            label: string;
            /** Match */
            match: number;
            /** Weight */
            weight: number;
        };
        /** ScreeningDecision */
        ScreeningDecision: {
            /** Decision */
            decision: string;
            /** Duplicate Group */
            duplicate_group?: string | null;
            /** Reason */
            reason: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "paper" | "policy" | "grant" | "person" | "facility" | "equipment" | "method" | "template" | "dataset";
        /** StudioRun */
        StudioRun: {
            capability: components["schemas"]["Capability"];
            /** Current Stage */
            current_stage: string;
            /** Durable Instance Id */
            durable_instance_id: string;
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Progress */
            progress: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            status: components["schemas"]["RunStatus"];
            /** Title */
            title: string;
        };
        /** StudioRunRequest */
        StudioRunRequest: {
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /** Objective */
            objective: string;
            /**
             * Online Research
             * @default false
             */
            online_research: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Active Runs */
            active_runs: number;
            /** Connector Ready */
            connector_ready: number;
            /** Connector Total */
            connector_total: number;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Library Items */
            library_items: number;
            /** Pending Approvals */
            pending_approvals: number;
            /** Persistence */
            persistence: string;
            project: components["schemas"]["ProjectSettings"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSetting"][];
                };
            };
        };
    };
    approvals_api_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"][];
                };
            };
        };
    };
    decide_approval_api_approvals__approval_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoke_assistant_api_assistant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitySpec"][];
                };
            };
        };
    };
    connectors_api_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSetting"][];
                };
            };
        };
    };
    update_connector_api_connectors__connector_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSetting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connector_api_connectors__connector_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSetting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_dataset_api_datasets_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetExecutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetExecutionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_dataset_api_datasets_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItem"][];
                };
            };
        };
    };
    ingest_library_item_api_library_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_library_item_api_library_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_library_item_api_library_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    run_capability_api_research__capability__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capability: components["schemas"]["Capability"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettings"];
                };
            };
        };
    };
    update_project_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_studio_api_studios__capability__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capability: components["schemas"]["Capability"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudioRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiteratureStudioResult"] | components["schemas"]["GrantStudioResult"] | components["schemas"]["MatchingStudioResult"] | components["schemas"]["DatasetStudioResult"] | components["schemas"]["InstitutionalStudioResult"] | components["schemas"]["AutomationStudioResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflows_api_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
