"""Append-only platform governance audit trail.

Persists ``AuditEvent`` records (ownership grants/revocations, approval
decisions, release cuts, deployment activation/deprecation/rollback, policy
gate failures, artifact deletions) to the dedicated ``agentStudioAuditV1``
container, partitioned by the same synthetic ``/scope_key`` used by the
metadata and memory containers, so retention/TTL for the audit trail is
governed independently from both.

This module is intentionally append-only: there is no update or delete
method on any store implementation, mirroring the durable, tamper-evident
nature of an audit trail. Callers that need to reference an event again
(for example a UI audit-log view) use ``list_events``.

The production factory raises ``AuditStoreUnavailableError`` when no Cosmos
endpoint is configured.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

from research_assistant_core.azure_auth import azure_credential

from research_assistant_api.agent_studio.models import AuditEvent, AuditEventKind
from research_assistant_api.agent_studio.scope import ScopeContext, compute_scope_key
from research_assistant_api.config import Settings

if TYPE_CHECKING:
    from azure.core.credentials import TokenCredential


class AuditStoreError(RuntimeError):
    pass


class AuditStoreUnavailableError(AuditStoreError):
    """Raised when the production audit store factory has no cloud backend
    configured. Never silently falls back to an in-memory store outside
    tests."""


class AuditStore(Protocol):
    def record(self, event: AuditEvent) -> AuditEvent: ...

    def list_events(
        self,
        *,
        scope: ScopeContext,
        logical_agent_id: str | None = None,
        kind: AuditEventKind | None = None,
        limit: int = 100,
    ) -> tuple[AuditEvent, ...]: ...


class CosmosAuditStore:
    """Cosmos DB-backed ``AuditStore``.

    Persists to the dedicated ``agentStudioAuditV1`` container, partitioned
    by ``/scope_key``. Every point write is a plain ``create_item`` (never
    ``upsert_item``: an audit event id is always freshly generated by the
    caller and a collision would indicate a bug, not a legitimate replace),
    and every query runs with an explicit ``partition_key=`` for exactly one
    ``(tenant_id, project_id)`` pair -- never
    ``enable_cross_partition_query=True``.
    """

    def __init__(
        self,
        endpoint: str,
        database_name: str,
        credential: TokenCredential,
        container_name: str = "agentStudioAuditV1",
    ) -> None:
        from azure.cosmos import CosmosClient  # local import: optional heavy dependency

        client = CosmosClient(endpoint, credential=credential)
        database = client.get_database_client(database_name)
        self._container = database.get_container_client(container_name)

    @staticmethod
    def _document(event: AuditEvent) -> dict[str, Any]:
        return {
            "id": event.id,
            "documentType": "audit_event",
            "scope_key": compute_scope_key(event.tenant_id, event.project_id),
            "tenantId": event.tenant_id,
            "projectId": event.project_id,
            "logicalAgentId": event.logical_agent_id,
            "kind": event.kind.value,
            "payload": event.model_dump(mode="json"),
        }

    def record(self, event: AuditEvent) -> AuditEvent:
        self._container.create_item(self._document(event))
        return event

    def list_events(
        self,
        *,
        scope: ScopeContext,
        logical_agent_id: str | None = None,
        kind: AuditEventKind | None = None,
        limit: int = 100,
    ) -> tuple[AuditEvent, ...]:
        query = "SELECT * FROM c WHERE c.documentType = @documentType"
        parameters: list[dict[str, Any]] = [{"name": "@documentType", "value": "audit_event"}]
        if logical_agent_id is not None:
            query += " AND c.logicalAgentId = @logicalAgentId"
            parameters.append({"name": "@logicalAgentId", "value": logical_agent_id})
        if kind is not None:
            query += " AND c.kind = @kind"
            parameters.append({"name": "@kind", "value": kind.value})
        documents = list(
            self._container.query_items(
                query=query,
                parameters=parameters,
                partition_key=compute_scope_key(scope.tenant_id, scope.project_id),
            )
        )
        events = [AuditEvent.model_validate(document["payload"]) for document in documents]
        events.sort(key=lambda event: event.created_at)
        return tuple(events[-limit:])


def build_audit_store(settings: Settings) -> AuditStore:
    """Production factory: never returns an in-memory store.

    Raises ``AuditStoreUnavailableError`` when no Cosmos endpoint is
    configured, rather than silently degrading to in-memory persistence.
    """
    if not settings.cosmos_endpoint:
        raise AuditStoreUnavailableError(
            "No Azure Cosmos DB endpoint is configured; Agent Studio audit persistence is unavailable."
        )
    credential = azure_credential(settings.managed_identity_client_id)
    return CosmosAuditStore(
        settings.cosmos_endpoint,
        settings.agent_studio_cosmos_database,
        credential,
        settings.agent_studio_audit_container,
    )


class AuditService:
    """Thin facade: mints ``AuditEvent`` ids/timestamps and writes through to
    the configured ``AuditStore``. Kept deliberately simple -- callers
    (release/deployment/approval services) supply the semantic ``kind``,
    ``subject_id``, and ``detail``; this service never infers meaning from
    the caller's own domain records.
    """

    def __init__(self, store: AuditStore) -> None:
        self._store = store

    def record(
        self,
        *,
        tenant_id: str,
        project_id: str,
        kind: AuditEventKind,
        actor_id: str,
        subject_id: str,
        logical_agent_id: str | None = None,
        detail: dict[str, str] | None = None,
    ) -> AuditEvent:
        from uuid import uuid4

        event = AuditEvent(
            id=str(uuid4()),
            tenant_id=tenant_id,
            project_id=project_id,
            logical_agent_id=logical_agent_id,
            kind=kind,
            actor_id=actor_id,
            subject_id=subject_id,
            detail=detail or {},
        )
        return self._store.record(event)

    def list_events(
        self,
        *,
        scope: ScopeContext,
        logical_agent_id: str | None = None,
        kind: AuditEventKind | None = None,
        limit: int = 100,
    ) -> tuple[AuditEvent, ...]:
        return self._store.list_events(scope=scope, logical_agent_id=logical_agent_id, kind=kind, limit=limit)
